//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave is a backupJobs application.
        /// </summary>
        internal static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Range of backup to execute.
        /// </summary>
        internal static string BackupIndexesOptionDescription {
            get {
                return ResourceManager.GetString("BackupIndexesOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type of backup (Complete or Differential).
        /// </summary>
        internal static string BackupTypeOptionDescription {
            get {
                return ResourceManager.GetString("BackupTypeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a comand : .
        /// </summary>
        internal static string ChooseCommand {
            get {
                return ResourceManager.GetString("ChooseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choosen language:.
        /// </summary>
        internal static string ChoosenLanguageCommand {
            get {
                return ResourceManager.GetString("ChoosenLanguageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The backup job is complete.
        /// </summary>
        internal static string CompleteBackup {
            get {
                return ResourceManager.GetString("CompleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy of file:.
        /// </summary>
        internal static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy of new file.
        /// </summary>
        internal static string CopyNewFile {
            get {
                return ResourceManager.GetString("CopyNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new backup job.
        /// </summary>
        internal static string CreateCommandDescription {
            get {
                return ResourceManager.GetString("CreateCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the specified backup.
        /// </summary>
        internal static string DeleteCommandDescription {
            get {
                return ResourceManager.GetString("DeleteCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The path of the destination directory.
        /// </summary>
        internal static string DestinationDirectoryPathOptionDescription {
            get {
                return ResourceManager.GetString("DestinationDirectoryPathOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The backup job is differential.
        /// </summary>
        internal static string DifferentialBackup {
            get {
                return ResourceManager.GetString("DifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à already exists in the target directory and is newer than the one selected. The copy will not be made..
        /// </summary>
        internal static string DontCopyFile {
            get {
                return ResourceManager.GetString("DontCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job ended..
        /// </summary>
        internal static string EndBackupJobExecutionMessage {
            get {
                return ResourceManager.GetString("EndBackupJobExecutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a command:.
        /// </summary>
        internal static string EnterCommand {
            get {
                return ResourceManager.GetString("EnterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Unknown language.
        /// </summary>
        internal static string ErrorLanguage1 {
            get {
                return ResourceManager.GetString("ErrorLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in language information.
        /// </summary>
        internal static string ErrorLanguage2 {
            get {
                return ResourceManager.GetString("ErrorLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The chosen language is already current..
        /// </summary>
        internal static string ErrorSameLanguage {
            get {
                return ResourceManager.GetString("ErrorSameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute one or more backup jobs.
        /// </summary>
        internal static string ExecuteCommandDescription {
            get {
                return ResourceManager.GetString("ExecuteCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HelloWorld.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the program&apos;s language.
        /// </summary>
        internal static string LanguageCommandDescription {
            get {
                return ResourceManager.GetString("LanguageCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The chosen language: &lt;en|fr&gt;.
        /// </summary>
        internal static string LanguageOptionDescription {
            get {
                return ResourceManager.GetString("LanguageOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name of the backup.
        /// </summary>
        internal static string NameOptionDescription {
            get {
                return ResourceManager.GetString("NameOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backupjobs with this name were found.
        /// </summary>
        internal static string NoBackupJobFound {
            get {
                return ResourceManager.GetString("NoBackupJobFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup job to execute.
        /// </summary>
        internal static string NoBackupJobToExecute {
            get {
                return ResourceManager.GetString("NoBackupJobToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Directory doesn&apos;t exist:.
        /// </summary>
        internal static string NoSourceDirMessage {
            get {
                return ResourceManager.GetString("NoSourceDirMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please restart your application for the changes to take effect.
        /// </summary>
        internal static string ResetAppAfterChangingLanguage {
            get {
                return ResourceManager.GetString("ResetAppAfterChangingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two backups can&apos;t have the same name.
        /// </summary>
        internal static string SameNameBackup {
            get {
                return ResourceManager.GetString("SameNameBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show all backups.
        /// </summary>
        internal static string ShowCommandDescription {
            get {
                return ResourceManager.GetString("ShowCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The path of the source directory.
        /// </summary>
        internal static string SourceDirectoryPathOptionDescription {
            get {
                return ResourceManager.GetString("SourceDirectoryPathOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CopyFileAndUpdateLog function entry.
        /// </summary>
        internal static string StartCopyFileAndUpdateLog {
            get {
                return ResourceManager.GetString("StartCopyFileAndUpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CopyFilesDifferential function entry.
        /// </summary>
        internal static string StartCopyFilesDifferential {
            get {
                return ResourceManager.GetString("StartCopyFilesDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution of backup job : .
        /// </summary>
        internal static string StartingBackupJobExecutionMessage {
            get {
                return ResourceManager.GetString("StartingBackupJobExecutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfuly deleted.
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file.
        /// </summary>
        internal static string TheFile {
            get {
                return ResourceManager.GetString("TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many backups already exist.
        /// </summary>
        internal static string TooManyBackup {
            get {
                return ResourceManager.GetString("TooManyBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The chosen language has been successfully updated:.
        /// </summary>
        internal static string UpdateLanguage {
            get {
                return ResourceManager.GetString("UpdateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the EasySave application, where you can make backups..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
